name: BigQuery Deployment
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Check BigQuery connection
        run: |
          bq version
          gcloud auth list
          
      - name: Execute SQL
        run: |
          for file in sql/*.sql; do
            echo "Executing $file"
            bq query \
              --use_legacy_sql=false \
              < "$file"
          done